"""
gen_bracket_data.py
Fetches the official 2026 FIFA World Cup third-place combination table from
Wikipedia (which mirrors FIFA's published Annex C), parses all 495 entries,
and prints the YAML block for tournament.yaml.

Run once from the project root:
    python scripts/gen_bracket_data.py >> /tmp/bracket_data.yaml
Then copy the output into config/tournament.yaml.
"""

import re
import urllib.request


WIKI_URL = (
    "https://en.wikipedia.org/w/index.php"
    "?title=Template:2026_FIFA_World_Cup_third-place_table&action=raw"
)

GROUPS = list("ABCDEFGHIJKL")
SLOTS  = list("ABDEGIKL")   # slot columns are: 1A,1B,1D,1E,1G,1I,1K,1L


def fetch_raw() -> str:
    req = urllib.request.Request(WIKI_URL, headers={"User-Agent": "wcpredict-setup/1.0"})
    with urllib.request.urlopen(req, timeout=20) as r:
        return r.read().decode("utf-8")


def parse(raw: str) -> list[tuple[str, dict[str, str]]]:
    """
    Returns a list of (group_key, slot_map) pairs.
    group_key  – 8-letter sorted string of advancing groups, e.g. "EFGHIJKL"
    slot_map   – dict mapping slot letter -> source group, e.g. {'A':'E', 'B':'J', ...}
    """
    # Normalise: collapse all whitespace to single spaces
    text = re.sub(r"\s+", " ", raw)

    # Each row is delimited by "|-" in wikitext.
    # We extract every segment that starts with "! scope=\"row\" |" (a data row).
    row_pat = re.compile(
        r'! scope="row" \| \d+ \| (.*?)(?=! scope="row"|\|\})',
        re.DOTALL,
    )
    entries: list[tuple[str, dict[str, str]]] = []

    for m in row_pat.finditer(text):
        body = m.group(1)

        # Remove the rowspan separator present only in the first row
        body = re.sub(r"! rowspan=\"\d+\" \|", "||", body)

        # Split on "||" and clean each cell
        cells = [c.strip() for c in body.split("||")]

        # Extract bold group letters from the first 12 cells
        advancing: list[str] = []
        for cell in cells[:12]:
            gm = re.search(r"'''([A-L])'''", cell)
            if gm:
                advancing.append(gm.group(1))

        if len(advancing) != 8:
            continue  # malformed – skip

        # Extract slot assignments from cells 12-19 (value like "3E")
        slot_vals: list[str] = []
        for cell in cells[12:20]:
            sm = re.search(r"3([A-L])", cell)
            if sm:
                slot_vals.append(sm.group(1))

        if len(slot_vals) != 8:
            continue

        group_key = "".join(sorted(advancing))
        slot_map  = dict(zip(SLOTS, slot_vals))
        entries.append((group_key, slot_map))

    return entries


def emit_yaml(entries: list[tuple[str, dict[str, str]]]) -> str:
    lines = ["third_place_allocation:"]
    lines.append(
        "  # Key: 8 advancing groups (sorted). "
        "Value: {slot: source_group} where slot is the winner group"
    )
    lines.append(
        "  # Slots: A=1A, B=1B, D=1D, E=1E, G=1G, I=1I, K=1K, L=1L"
    )
    for group_key, slot_map in entries:
        vals = ", ".join(f"{s}: {v}" for s, v in sorted(slot_map.items()))
        lines.append(f"  {group_key}: {{{vals}}}")
    return "\n".join(lines)


def main() -> None:
    print("# Auto-generated by scripts/gen_bracket_data.py", flush=True)
    print("# Source: Wikipedia Template:2026 FIFA World Cup third-place table", flush=True)
    print("# (which mirrors FIFA's published Annex C, all 495 combinations)", flush=True)
    print(flush=True)

    print("round_of_32_slots:", flush=True)
    print("  # Fixed pairings (winner/runner-up only, no third-placed team):", flush=True)
    print("  fixed:", flush=True)
    fixed = [
        ["2A", "2B"],
        ["1C", "2F"],
        ["1F", "2C"],
        ["2E", "2I"],
        ["1H", "2J"],
        ["2K", "2L"],
        ["2D", "2G"],
        ["1J", "2H"],
    ]
    for pair in fixed:
        print(f"    - [{pair[0]}, {pair[1]}]", flush=True)
    print("  # Variable pairings: winner of slot group vs best-third from allowed pool", flush=True)
    print("  third_place_slots:", flush=True)
    slots_def = {
        "A": ["C", "E", "F", "H", "I"],
        "B": ["E", "F", "G", "I", "J"],
        "D": ["B", "E", "F", "I", "J"],
        "E": ["A", "B", "C", "D", "F"],
        "G": ["A", "E", "H", "I", "J"],
        "I": ["C", "D", "F", "G", "H"],
        "K": ["D", "E", "I", "J", "L"],
        "L": ["E", "H", "I", "J", "K"],
    }
    for slot, pool in sorted(slots_def.items()):
        print(f"    {slot}: [{', '.join(pool)}]", flush=True)
    print(flush=True)

    import sys
    print("Fetching Wikipedia template...", file=sys.stderr, flush=True)
    raw = fetch_raw()
    entries = parse(raw)
    print(f"Parsed {len(entries)} combinations.", file=sys.stderr, flush=True)
    assert len(entries) == 495, f"Expected 495, got {len(entries)}"

    print(emit_yaml(entries), flush=True)
    print(f"\n# Total combinations: {len(entries)}", flush=True)


if __name__ == "__main__":
    main()
